server:
  port: 0

spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:ewm-db}:${POSTGRES_PORT:5432}/ewm-main
    username: ${POSTGRES_USER:main}
    password: ${POSTGRES_PASSWORD:main}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
      properties:
        hibernate:
          format_sql: true
          show_sql: false
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

ewm:
  stats-server:
    id: stats-server

logging:
  level:
    root: INFO
    org.springframework.cloud.loadbalancer: DEBUG