services:

  discovery-server:
    build: infra/discovery-server
    image: ewm-discovery-server
    container_name: discovery-server
    ports:
      - "8761:8761"
    healthcheck:
      test: wget -q --spider http://localhost:8761/actuator/health || exit 1
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  config-server:
    build: infra/config-server
    image: ewm-config-server
    container_name: config-server
    depends_on:
      discovery-server:
        condition: service_healthy
    ports:
      - "8888:8888"
    environment:
      - SERVER_PORT=8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
    healthcheck:
      test: wget -q --spider http://localhost:8888/actuator/health || exit 1
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  gateway-server:
    build: infra/gateway-server
    image: ewm-gateway-server
    container_name: gateway-server
    depends_on:
      config-server:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/


  stats-db:
    image: postgres:16.1
    container_name: stats-db-postgres
    volumes:
      - ./stats/stats-server/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=stats
      - POSTGRES_PASSWORD=stats
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  ewm-db:
    image: postgres:16.1
    container_name: ewm-db-postgres
    volumes:
      - ./core/main-service/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/02-schema.sql
    ports:
      - "6543:5432"
    environment:
      - POSTGRES_DB=ewm-main
      - POSTGRES_USER=main
      - POSTGRES_PASSWORD=main
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10


  stats-server:
    build: stats/stats-server
    image: ewm-stats-server
    container_name: stats-server
    depends_on:
      config-server:
        condition: service_healthy
      stats-db:
        condition: service_healthy
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - POSTGRES_HOST=stats-db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=stats
      - POSTGRES_PASSWORD=stats
      - SPRING_SQL_INIT_MODE=always

  main-service:
    build: core/main-service
    image: ewm-main-service
    container_name: main-service
    depends_on:
      config-server:
        condition: service_healthy
      ewm-db:
        condition: service_healthy
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - POSTGRES_HOST=ewm-db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=main
      - POSTGRES_PASSWORD=main