server:
  port: 0

spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:user-db}:${POSTGRES_PORT:5432}/ewm-users
    username: ${POSTGRES_USER:users}
    password: ${POSTGRES_PASSWORD:users}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
      properties:
        hibernate:
          format_sql: true
          show_sql: false
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:discovery-server}:${EUREKA_PORT:8761}/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    root: INFO
