server:
  port: 9090

spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:stats-db}:${POSTGRES_PORT:5432}/stats
    username: ${POSTGRES_USER:stats}
    password: ${POSTGRES_PASSWORD:stats}
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:discovery-server}:${EUREKA_PORT:8761}/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    root: INFO