CREATE TABLE IF NOT EXISTS users(
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name  VARCHAR(250),
    email VARCHAR(254) UNIQUE
);

CREATE TABLE IF NOT EXISTS categories(
    id   BIGINT      GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS events (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_on         TIMESTAMP         NOT NULL DEFAULT CURRENT_TIMESTAMP,
    title              VARCHAR(120)      NOT NULL,
    annotation         VARCHAR(2000)     NOT NULL,
    description        VARCHAR(7000)     NOT NULL,
    event_date         TIMESTAMP         NOT NULL,
    state              VARCHAR(20)       NOT NULL DEFAULT 'PENDING',
    paid               BOOL              NOT NULL DEFAULT false,
    participant_limit  INT               NOT NULL DEFAULT 0,
    request_moderation BOOL              NOT NULL DEFAULT true,
    category_id        BIGINT            NOT NULL,
    initiator_id       BIGINT            NOT NULL,
    lat                DOUBLE PRECISION  NOT NULL,
    lon                DOUBLE PRECISION  NOT NULL,
    published_on       TIMESTAMP,

    CONSTRAINT events_category_id_fk     FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE RESTRICT,
    CONSTRAINT events_initiator_id_fk    FOREIGN KEY (initiator_id) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT events_date_is_future     CHECK (event_date > CURRENT_DATE),
    CONSTRAINT events_state_check        CHECK (state IN ('PUBLISHED', 'PENDING', 'CANCELED')),
    CONSTRAINT events_published_on_check CHECK (
        (state = 'PUBLISHED' AND published_on IS NOT NULL) OR
        (state != 'PUBLISHED')
    )
);

CREATE TABLE IF NOT EXISTS participation_requests (
    id        BIGINT    GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    created   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    event_id  BIGINT    NOT NULL REFERENCES events(id) ON DELETE CASCADE,
    requester BIGINT    NOT NULL REFERENCES users(id)  ON DELETE CASCADE,
    status    VARCHAR   NOT NULL
);

CREATE TABLE IF NOT EXISTS compilations(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pinned BOOLEAN,
    title  VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS compilation_event(
    compilation_id BIGINT REFERENCES compilations(id),
    event_id       BIGINT REFERENCES events(id),
                   PRIMARY KEY (compilation_id, event_id)
);

CREATE TABLE IF NOT EXISTS comments(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text       VARCHAR(2000) NOT NULL,
    author_id  BIGINT        NOT NULL,
    created_on TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    event_id   BIGINT        NOT NULL,

    CONSTRAINT comments_author_id_fk        FOREIGN KEY (author_id) REFERENCES users(id)  ON DELETE CASCADE,
    CONSTRAINT comments_event_id_fk         FOREIGN KEY (event_id)  REFERENCES events(id) ON DELETE CASCADE
);